name: Build & Deploy Develop
on:
  workflow_call:

jobs:

  reusable_workflow_job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: 14.19
          
      - name: Install
        run: npm install
      
      - name: Install Cyclone
        run: npm install --save-dev @cyclonedx/cyclonedx-npm

      - run: npm run lint
      - run: npm run test:coverage
      - run: npx  @cyclonedx/cyclonedx-npm  --output-format XML --output-file bom.xml --mc-type application

      - name: Process Deptrack URL
        shell: bash
        run: |
          pattern='^(([[:alnum:]]+):\/\/)?(([[:alnum:]]+)@)?([^:^@\/]+)(:([[:digit:]]+))?(\/?[^:^@]?)$'
          if [[ "${{ secrets.DEPTRACK_URL }}" =~ $pattern ]]; then
              export DEPTRACK_HOST=${BASH_REMATCH[5]}
              echo "DEPTRACK_HOST=${DEPTRACK_HOST}" >> $GITHUB_ENV
          else
              echo "URL did not match pattern: $url"
              exit 1
          fi

      - name: Send SBOM to DepTrack
        uses: DependencyTrack/gh-upload-sbom@v3.0.0
        with:
          serverhostname: ${{ env.DEPTRACK_HOST }}
          apikey: ${{ secrets.DEPTRACK_API_KEY }}
          protocol: https
          projectname: ${{ env.PROJECT_NAME }}
          projectversion: ${{ env.REVISION }}
          bomfilename: "target/bom.json"
          autocreate: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate version file with hash
        run: git rev-parse --short HEAD > git-commit-version.txt &&
          date +"%D %T" >> git-commit-version.txt &&
          echo ${{github.ref}} >> git-commit-version.txt

      - name: Deploy-develop
        run: |
          npm run build
          cp git-commit-version.txt dist/
          aws s3 cp \
            --recursive \
            --region us-east-1 \
            ./dist s3://front-farm-plataforma/${{ secrets.MFE_CONTEXT }}

      - name: Invalidate-cf-develop
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.CF_DEV }}
          PATHS: "/${{ secrets.MFE_CONTEXT }}/*"
