name: Upgrade version Workflow

on:
  workflow_call:
    inputs:
      choice:
        description: Patch/Minor/Major
        required: true
        type: string

jobs:
  reusable_workflow_job:
    name: Reusable upgrade version workflow
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo ${{ inputs.choice }}
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v3
        with:
          node-version: 14.19

      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"

      - name: Upgrade version in package.json
        run: npm version ${{ inputs.choice }} --no-git-tag-version -m "v%s"

      - name: Get version from package.json
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Echo version from package.json
        run: echo ${{ env.PACKAGE_VERSION }}
        
      - name: Create PR from chore branch to develop
        run: |
          touch package.json
          git add -A
          git commit -m "Update package.json - new version v${{ env.PACKAGE_VERSION }} [skip ci]"
          git push -u origin develop:chore-newversion_${{ env.PACKAGE_VERSION }}

      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "chore-newversion_${{ env.PACKAGE_VERSION }}"
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automerge,triggered pr"
          pr_title: "Pulling chore-newversion_${{ env.PACKAGE_VERSION }} into develop [skip ci]"
