name: Vue 3 PR from tag into releases
on:
  workflow_call:
    inputs:
      tag:
        description: "Tag name"
        required: true
        type: string

jobs:
  reusable_workflow_job:
    name: Reusable PR from tag into releases workflow
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"

      - name: Reset head to tag
        run: |
          git reset --hard ${{ inputs.tag }}

      - name: Push to new branch
        run: |
          git push -u origin develop:release-${{ inputs.tag }}-into-releases

      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "release-${{ inputs.tag }}-into-releases"
          destination_branch: "releases"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automerge,triggered pr"
          pr_title: "Pulling ${{ inputs.tag }} into releases"
