name: Vue 3 PR from tag into releases
on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag name'
        required: true
        type: string

jobs:
  reusable_workflow_job:
    name: Reusable PR from tag into releases workflow
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 10
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"

      - name: Reset head to tag
        run: |
          git reset --hard ${{ inputs.tag }}
      
          - name: Generate version file with hash
          run: git rev-parse --short HEAD > git-commit-version.txt &&
            date +"%D %T" >> git-commit-version.txt
  
      - name: Deploy-uat
        run: |
          npm run build
          cp git-commit-version.txt dist/
          aws s3 cp \
            --recursive \
            --region us-east-1 \
            ./dist s3://front-farm-plataforma-uat/${{ secrets.MFE_CONTEXT }}

      - name: Invalidate-cf-uat
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.CF_UAT }}
          PATHS: "/${{ secrets.MFE_CONTEXT }}/*"

     