name: Vue 3 Upgrade version Workflow

on:
  workflow_call:
    inputs:
      choice:
        description: Patch/Minor/Major
        required: true
        type: string

jobs:
  reusable_workflow_job:
    name: Reusable upgrade version workflow
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    environment: production
    steps:
      - run: echo ${{ inputs.choice }}
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"

      - name: Upgrade version in package.json
        run: npm version ${{ inputs.choice }} --no-git-tag-version -m "v%s"

      - name: Get version from package.json
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Echo version from package.json
        run: echo ${{ env.PACKAGE_VERSION }}

      - name: Commit new package.json
        uses: stefanzweifel/git-auto-commit-action@v5
      
      - name: Create tag using value from package.json
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
